### ISSUE TITLE
How to use "hanaOptions"?

### ISSUE THREAD

**Issue by wschoe2020** [SAP/sap-hana-driver-for-sqltools#106]
I want to use a LOCALE Property(SQLDBC Connection Properties).
(Ref. https://help.sap.com/viewer/1efad1691c1f496b8b580064a6536c2d/LATEST/en-US/4fe9978ebac44f35b9369ef5a4a26f4c.html )
I want help.

**Comment by wschoe2020** [comment]
> I want to use a LOCALE Property(SQLDBC Connection Properties).
> (Ref. https://help.sap.com/viewer/1efad1691c1f496b8b580064a6536c2d/LATEST/en-US/4fe9978ebac44f35b9369ef5a4a26f4c.html )
> I want help.

Fortunately, I looked at other sqltools db addons and found a way. I salute you for your products.
        {
            "dialect": "SAPHana",
            "port": 443,
            "server": "hanadevserver.hana.prod-jp10.hanacloud.ondemand.com",
            "name": "hdi-server-ko",
            "database": "myhdischema",
            "username": "myhdischema_username_RT",
            "password": "mypassword_RT",
            "hanaOptions":{"LOCALE":"ko"},
            "isActive": true,
            "isConnected": true,
            "connectionTimeout": 60
        }

**Comment by ariel-bentu** [comment]
Thanks for the compliments (you may also star us :-))
