### ISSUE TITLE
Unable to install it under Business Application Studio

### ISSUE THREAD

**Issue by ivanmir** [SAP/sap-hana-driver-for-sqltools#132]
Hi,

I am trying to install/update the HANA SQL Driver using the following procedure:
https://blogs.sap.com/2020/04/12/how-to-install-a-vs-code-extension-to-sap-business-application-studio/

The extension is installed, but it issues the following error:
Activating extension 'SAP HANA Driver for SQLTools' failed: Cannot read property 'registerPlugin' of undefined

The reason why I want this is because in Business Application Studio, the HANA driver doesn't have a way to specify a certificate for SSL connection encryption. 

Please advise.

Best regards,
Ivan

**Comment by offer8** [comment]
Hi @ivanmir 

Thanks for the feedback.
BAS is currently pre-defined with an older SQL Tools version which already contain the HANA Driver in it.

You can gave the possibility to specify certificate for SSL connection.
Please follow this blog:
https://blogs.sap.com/2020/04/22/creating-an-encrypted-connection-to-hana-as-a-service-and-hana-cloud-service-instances-in-business-application-studio/

Regards,
Offer.
