### ISSUE TITLE
Publish to VSCode marketplace

### ISSUE THREAD

**Issue by mtxr** [SAP/sap-hana-driver-for-sqltools#16]
Hi all!

Awesome work on this extension! I took a quick look and it's pretty amazing you are working on this.
I've tried to make the extension API easier and pluggable as much as possible so if you have any feedback about it, please let me know.

I just noticed the marketplace link is not working, but I strongly encourage you to publish it to make it easier to find for the users directly from VSCode. Here is MS Guide for that: https://code.visualstudio.com/api/working-with-extensions/publishing-extension. Also, I'm here to support you if you need it.

If possible, submit a PR to https://github.com/mtxr/vscode-sqltools updating these files to list your driver:

- https://github.com/mtxr/vscode-sqltools/blob/master/README.md
- https://github.com/mtxr/vscode-sqltools/blob/master/docs/src/pages/contributing/support-new-drivers.mdx

Thank you, guys!

🍻

**Comment by offer8** [comment]
Hi @mtxr 
We are in the middle of the process to release it to market place.

Actually it is a good opportunity to ask you to check something.
During testing the SAP Hana driver and also other existing drivers such as MariaDB, MSSQL 
The status icons (active, inactive, default) are not showing in the connections pane although they are packaged correctly in the driver VSIX.
I tested it with latest vscode-sqltools version and several VSCode versions from April till now.

Could you please check if this is a known issue.
Feel free to take the current release of [sap-hana-driver-for-sqltools version 0.2.0](https://github.com/SAP/sap-hana-driver-for-sqltools/releases/download/v0.2.0/sap-hana-driver-for-sqltools-0.2.0.vsix)

Thanks!

**Comment by ariel-bentu** [comment]
Hi @mtxr,
regarding the icons issue, one more piece of info: on (my) Mac it works and the icons show, but on windows machines or in browser running Eclipse Theia - they don't show up.

**Comment by mtxr** [comment]
@ariel-bentu @offer8 I've opened an issue so I can track it there.
Since you've published already, I'll close this issue. Great job you all!
