### ISSUE TITLE
Unable to export query results. Command doesn't appear to be resolving. EXECUTING COMMAND => sqltools.saveResults

### ISSUE THREAD

**Issue by hannon90** [SAP/sap-hana-driver-for-sqltools#200]
This tool is awesome, though I have been unable to export any of the query results to CSV. I have tried setting the default export settings in the JSON using:

sqltools.defaultExportType = 'csv'

I have also tried just using the export/open button in the query results window. I'm not entirely sure, but it doesn't appear that the command is resolving: EXECUTING COMMAND => sqltools.saveResults. There is not request received afterwards. 

This could be my naivete, so forgive me if I'm missing the obvious.

**Comment by ariel-bentu** [comment]
Hi, this is the wrong repo. The problem you describe is related to SQL Tools and not to the HANA driver for it. Please open in https://github.com/mtxr/vscode-sqltools
