### ISSUE TITLE
Issue with errno 3221226356

### ISSUE THREAD

**Issue by StefanButscher** [SAP/sap-hana-driver-for-sqltools#202]
Hello,

I have installed SAP HANA Driver for SQLTools from the marketplace in VS code. Upon tying to connect I get the notification that 
"You need to install "@sap/hana-client@latest" to connect to". If I click on install I end up in an error, with the error message in the log:
 
134 error code ELIFECYCLE
135 error errno 3221226356
136 error @sap/hana-client@2.11.11-ms install: `node checkbuild.js`
136 error Exit status 3221226356
137 error Failed at the @sap/hana-client@2.11.11-ms install script.
137 error This is probably not a problem with npm. There is likely additional logging output above.
138 verbose exit [ 3221226356, true ]

This gives me no hint on what is wrong or how to proceed. Please provide some guidance and I would volunteer to start a troubleshooting section on the repo.

Thanks and Best Regards,
Stefan

**Comment by ariel-bentu** [comment]
The SAP HANA Driver defines to the host vscode-extension (SQL Tools) that it needs `@sap/hana-client` nom module. the rest is done by the SQL Tools.
I find it weird that it tried to install version 2.11... as the latest now is 2.10.15.

I suggest you try installing this module globally on your machine: `npm install -g @sap/hana-client` and see if this helps

**Comment by StefanButscher** [comment]
Hi,

thanks for the hint. I ran the command , same issue :-(

PS C:\Users\D050449\OneDrive - SAP SE\Agile\Hana@VScode> npm install -g @sap/hana-client

> @sap/hana-client@2.10.20 install C:\Users\D050449\AppData\Roaming\npm\node_modules\@sap\hana-client
> node checkbuild.js

npm ERR! code ELIFECYCLE
npm ERR! errno 3221226356
npm ERR! @sap/hana-client@2.10.20 install: `node checkbuild.js`
npm ERR! Exit status 3221226356
npm ERR!
npm ERR! Failed at the @sap/hana-client@2.10.20 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\D050449\AppData\Roaming\npm-cache\_logs\2021-11-15T07_23_32_052Z-debug.log
PS C:\Users\D050449\OneDrive - SAP SE\Agile\Hana@VScode> 

*Then* I ran a general update of npm Same issue. 
->So I have no idea on how to proceed.

**Comment by ariel-bentu** [comment]
as we now know this is not related to the SQL Tools HANA driver, but to the driver installation itself, I suggest you open an issue in their repo.
See here for more info: https://github.com/SAP/node-hdb#sap-support-for-hdb-and-saphana-client
